### ISSUE TITLE
Erro na leitura de arquivo '/tmp/scielo/public/article_data.txt'

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_webservices#4]
(pulsemob_webservices)[gandalf@pulsemob pulsemob_webservices]$ python harvest_job.py
2016-03-10 14:01:44,715 Extracting articles from webservice (page 0)...
2016-03-10 14:01:44,957 Starting new HTTP connection (1): articlemeta.scielo.org
2016-03-10 14:01:44,964 "GET /api/v1/article/identifiers?offset=0 HTTP/1.1" 302 205
2016-03-10 14:01:45,325 "GET /api/v1/article/identifiers/?offset=0 HTTP/1.1" 200 133145
2016-03-10 14:01:45,345 Processing data...
Traceback (most recent call last):
  File "harvest_job.py", line 52, in <module>
    (add_update_article_entry, delete_article_entry)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 170, in harvest
    store_and_process_data_from_file(curs, input_file, data_table_name, temp_table)
  File "/var/www/pulsemob_webservices/pulsemob_webservices/harvest.py", line 70, in store_and_process_data_from_file
    curs.copy_from(open(r'{0}'.format(input_filepath), 'r'), temp_table, sep=',')
IOError: [Errno 2] No such file or directory: '/tmp/scielo/public/article_data.txt'

**Comment by fabiobatalha** [comment]
O script não considera que o arquivo pode não existir.
curs.copy_from(open(r'{0}'.format(input_filepath), 'r'), temp_table, sep=',')

quem gera esse arquivo?

**Comment by fabiobatalha** [comment]
Outro ponto é:

Se os paths para para **pg_shared_folder_output** e **pg_shared_folder_input** podem ser modificados no arquivo de configuração, seria interessante que o harvester fosse capaz de criar os diretórios quando estes não existirem (desde que o executor do script tenha permissão para tal).

**Comment by ghost** [comment]
@fabiobatalha, você está correto sobre a questão de criação do diretório. Já corrigi e subi uma alteração.

Com relação ao arquivo não encontrado, percebi que os caminhos _pg_shared_folder_output_ e _pg_shared_folder_input _devem ser os mesmos. Desenvolvemos no Windows com acesso externo, por isso precisamos de usar dois parâmetros (nesse caso, eles eram diferentes).

**Comment by fabiobatalha** [comment]
Considerando que as ferramentas serão utilizadas no Linux, vocês podem corrigir isso?

**Comment by ghost** [comment]
@fabiobatalha, me expressei mal. Me desculpe. Basta colocar esses dois parâmetros iguais.

O path _pg_shared_folder_output_ é utilizado para escrever o arquivo a partir do servidor em que se encontra o pulsemob_webservices. Já o path _pg_shared_folder_input_ é utilizado para acessar o arquivo escrito a partir do servidor em que se encontra o banco de dados. Como nesse caso, eles se encontram no mesmo servidor, basta que esses parâmetros apontem para o mesmo caminhe. Não há bug.

**Comment by fabiobatalha** [comment]
@carlosecbraga 

Ok, resta então corrigir a questão de criação dos diretórios quando configurado um path que não existe.

PS: o harvester esta funcionando com a configuração correta.

**Comment by ghost** [comment]
@fabiobatalha isso já foi corrigido na semana passada mesmo.
