### ISSUE TITLE
Erro ao salvar capa de Artigo

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/pulsemob_webservices#6]
Ao tentar salvar uma capa de artigo recebemos o seguinte erro na interface.

![screen shot 2016-03-23 at 6 07 34 pm](https://cloud.githubusercontent.com/assets/504142/14000910/2472cfbc-f122-11e5-9407-0be71071b065.png)

O log do django apresenta o seguinte erro.

[23/Mar/2016 21:05:59] INFO (views): Handling /backoffice/articles/upload-cover.
[23/Mar/2016 21:05:59] ERROR (solr_service): An exceptions was thrown while adding an article. Exception: HTTP code=409, reason=Conflict

**Comment by leobueno** [comment]
Este erro ocorreu porque houve uma modificação no mesmo registro do solr entre o tempo de leitura do registro e a atualização com a nova capa (O solr utiliza optimistic locking para prevenir que alguma atualização seja sobrescrita indevidamente)

Vejo 3 alternativas para resolver isto:
1. Pedir para o solr sobrescrever a alteração anterior (Não acho legal, podemos perder informação da outra atualização, pois temos que submeter sempre o documento completo, com todas as informações do artigo e não só a capa, e algum destes outros dados pode ter sido alterado além da capa).
2. Informar ao usuário o que ocorreu, recarregando a tela com os novos dados (Alguém pode ter atualizado a imagem da capa!) e solicitar que ele repita a operação caso deseje
3. Realizar uma nova consulta pelo ID do documento e submeter nova requisição de atualização trocando apenas a capa

Acho que as opções 2 ou 3 seriam as mais indicadas. Como desejam que a gente resolva este problema?

**Comment by scielo** [comment]
Ok @leobueno,

Acredito que isso possa ter ocorrido pois o harvester foi interrompido no
meio e provavelmente não fez o commit das mudanças e essa ação ainda esta
pendente de se executar.

Se isso for plausível, vou avaliar isso antes de seguir com as suas
sugestões.

**Comment by fabiobatalha** [comment]
@leobueno 

Foi exatamente isso o que aconteceu. Como o Harvester não terminou a execução, ficou pendente a execução de commit e optimize do indice.

Um novo ticket foi aberto para garantir a resiliência do processamento de harvesting.

#7
